target 'Demo' do
  platform :ios, '12.4'

  pod 'RestService', :path => '../', :testspecs => ['Tests']
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
    end
  end
end
